# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/aidag/Downloads/Hackster-master/Hackster-master/Sobel_zybo_z7/block_compile.srcs/constrs_1/new/cosnt.xdc

# Block Designs: bd/filtro/filtro.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro || ORIG_REF_NAME==filtro} -quiet] -quiet

# IP: bd/filtro/ip/filtro_processing_system7_0_0/filtro_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_processing_system7_0_0 || ORIG_REF_NAME==filtro_processing_system7_0_0} -quiet] -quiet

# IP: bd/filtro/ip/filtro_image_filter_0_0/filtro_image_filter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_image_filter_0_0 || ORIG_REF_NAME==filtro_image_filter_0_0} -quiet] -quiet

# IP: bd/filtro/ip/filtro_axi_vdma_0_0/filtro_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_axi_vdma_0_0 || ORIG_REF_NAME==filtro_axi_vdma_0_0} -quiet] -quiet

# IP: bd/filtro/ip/filtro_xbar_1/filtro_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_xbar_1 || ORIG_REF_NAME==filtro_xbar_1} -quiet] -quiet

# IP: bd/filtro/ip/filtro_axi_interconnect_0_0/filtro_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_axi_interconnect_0_0 || ORIG_REF_NAME==filtro_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/filtro/ip/filtro_axi_gpio_0_0/filtro_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_axi_gpio_0_0 || ORIG_REF_NAME==filtro_axi_gpio_0_0} -quiet] -quiet

# IP: bd/filtro/ip/filtro_rst_ps7_0_100M_0/filtro_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_rst_ps7_0_100M_0 || ORIG_REF_NAME==filtro_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/filtro/ip/filtro_auto_pc_0/filtro_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filtro_auto_pc_0 || ORIG_REF_NAME==filtro_auto_pc_0} -quiet] -quiet

# XDC: bd/filtro/filtro_ooc.xdc
