// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state7 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond460_i_reg_1443;
reg   [0:0] or_cond_i_i_reg_1452;
reg   [0:0] icmp_reg_1408;
reg   [0:0] tmp_s_reg_1399;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_i_reg_1486;
reg   [0:0] or_cond_i_reg_1486_pp0_iter2_reg;
reg   [7:0] t_V_2_reg_285;
wire   [0:0] exitcond461_i_fu_300_p2;
wire    ap_CS_fsm_state2;
wire   [7:0] i_V_fu_306_p2;
reg   [7:0] i_V_reg_1394;
wire   [0:0] tmp_s_fu_312_p2;
wire   [0:0] tmp_424_0_not_fu_318_p2;
reg   [0:0] tmp_424_0_not_reg_1403;
wire   [0:0] icmp_fu_334_p2;
wire   [0:0] tmp_2_fu_340_p2;
reg   [0:0] tmp_2_reg_1413;
wire   [0:0] tmp_468_1_fu_346_p2;
reg   [0:0] tmp_468_1_reg_1417;
wire   [0:0] tmp_3_fu_352_p2;
reg   [0:0] tmp_3_reg_1421;
wire   [1:0] row_assign_13_0_t_fu_506_p2;
reg   [1:0] row_assign_13_0_t_reg_1428;
wire   [1:0] row_assign_13_1_t_fu_544_p2;
reg   [1:0] row_assign_13_1_t_reg_1433;
wire   [1:0] row_assign_13_2_t_fu_582_p2;
reg   [1:0] row_assign_13_2_t_reg_1438;
wire   [0:0] exitcond460_i_fu_592_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_predicate_op147_read_state4;
reg    ap_predicate_op158_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond460_i_reg_1443_pp0_iter1_reg;
wire   [7:0] j_V_fu_598_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_650_p2;
wire   [1:0] tmp_43_fu_740_p1;
reg   [1:0] tmp_43_reg_1456;
wire   [0:0] brmerge_fu_744_p2;
reg   [0:0] brmerge_reg_1461;
reg   [7:0] k_buf_0_val_3_addr_reg_1468;
reg   [7:0] k_buf_0_val_4_addr_reg_1474;
reg   [7:0] k_buf_0_val_5_addr_reg_1480;
wire   [0:0] or_cond_i_fu_756_p2;
reg   [0:0] or_cond_i_reg_1486_pp0_iter1_reg;
wire   [7:0] src_kernel_win_0_va_6_fu_888_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_1490;
wire   [7:0] src_kernel_win_0_va_7_fu_906_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_1496;
wire   [7:0] src_kernel_win_0_va_8_fu_924_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_1502;
wire   [20:0] r_V_52_1_1_fu_1280_p2;
reg   [20:0] r_V_52_1_1_reg_1508;
reg   [7:0] src_kernel_win_0_va_16_reg_1513;
wire   [25:0] sum_V_2_fu_1106_p2;
reg   [25:0] sum_V_2_reg_1518;
wire   [24:0] grp_fu_1305_p3;
reg   [24:0] tmp5_reg_1523;
reg    ap_enable_reg_pp0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter1_state4;
wire   [7:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [7:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [7:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [7:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [7:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [7:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [7:0] t_V_reg_274;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_26_fu_749_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_148;
reg   [7:0] src_kernel_win_0_va_1_fu_152;
reg   [7:0] src_kernel_win_0_va_2_fu_156;
reg   [7:0] src_kernel_win_0_va_3_fu_160;
reg   [7:0] src_kernel_win_0_va_4_fu_164;
reg   [7:0] src_kernel_win_0_va_5_fu_168;
reg   [7:0] right_border_buf_0_s_fu_172;
wire   [7:0] col_buf_0_val_0_0_fu_796_p3;
reg   [7:0] right_border_buf_0_1_fu_176;
reg   [7:0] right_border_buf_0_2_fu_180;
reg   [7:0] right_border_buf_0_3_fu_184;
wire   [7:0] col_buf_0_val_1_0_fu_815_p3;
reg   [7:0] right_border_buf_0_4_fu_188;
reg   [7:0] right_border_buf_0_5_fu_192;
wire   [7:0] col_buf_0_val_2_0_fu_834_p3;
wire   [6:0] tmp_6_fu_324_p4;
wire   [8:0] t_V_cast_fu_296_p1;
wire   [1:0] tmp_8_fu_358_p1;
wire   [8:0] tmp_5_fu_362_p2;
wire   [0:0] tmp_10_fu_374_p3;
wire   [0:0] tmp_7_fu_388_p2;
wire   [0:0] rev_fu_382_p2;
wire   [0:0] tmp_11_fu_400_p3;
wire   [8:0] p_assign_s_fu_408_p2;
wire   [8:0] p_p2_i497_i_fu_414_p3;
wire   [1:0] tmp_12_fu_422_p1;
wire   [8:0] p_assign_14_1_fu_438_p2;
wire   [8:0] p_assign_14_2_fu_464_p2;
wire   [0:0] tmp_9_fu_426_p2;
wire   [1:0] p_assign_1_fu_432_p2;
wire   [0:0] or_cond_i496_i_fu_394_p2;
wire   [1:0] tmp_72_cast_fu_368_p2;
wire   [1:0] p_p2_i497_i_p_assign_s_fu_490_p3;
wire   [1:0] y_fu_498_p3;
wire   [1:0] tmp_20_fu_460_p1;
wire   [0:0] tmp_15_fu_452_p3;
wire   [1:0] tmp_27_fu_518_p2;
wire   [1:0] tmp_29_fu_524_p1;
wire   [0:0] tmp_14_fu_444_p3;
wire   [1:0] tmp_4_fu_528_p3;
wire   [1:0] tmp_1_fu_512_p2;
wire   [1:0] tmp_13_fu_536_p3;
wire   [1:0] tmp_25_fu_486_p1;
wire   [0:0] tmp_24_fu_478_p3;
wire   [1:0] tmp_38_fu_556_p2;
wire   [1:0] tmp_39_fu_562_p1;
wire   [0:0] tmp_21_fu_470_p3;
wire   [1:0] tmp_17_fu_566_p3;
wire   [1:0] tmp_16_fu_550_p2;
wire   [1:0] tmp_18_fu_574_p3;
wire   [6:0] tmp_40_fu_604_p4;
wire   [8:0] t_V_3_cast_fu_588_p1;
wire  signed [8:0] ImagLoc_x_fu_620_p2;
wire   [0:0] tmp_41_fu_630_p3;
wire   [0:0] tmp_22_fu_644_p2;
wire   [0:0] rev1_fu_638_p2;
wire   [0:0] tmp_42_fu_656_p3;
wire   [8:0] p_assign_3_fu_664_p2;
wire  signed [8:0] p_p2_i_i_fu_670_p3;
wire  signed [9:0] p_p2_i_i_cast_fu_682_p1;
wire  signed [9:0] ImagLoc_x_cast_fu_626_p1;
wire   [9:0] p_assign_4_fu_692_p2;
wire   [9:0] p_assign_5_fu_698_p3;
wire   [0:0] tmp_26_not_fu_710_p2;
wire   [0:0] tmp_23_fu_686_p2;
wire   [0:0] sel_tmp7_fu_716_p2;
wire   [0:0] sel_tmp8_fu_722_p2;
wire  signed [10:0] p_p2_i_i_cast6_fu_678_p1;
wire   [10:0] sel_tmp_cast_fu_706_p1;
wire  signed [10:0] x_fu_728_p3;
wire  signed [31:0] col_assign_cast_fu_736_p1;
wire   [0:0] icmp1_fu_614_p2;
wire   [1:0] col_assign_6_t_fu_779_p2;
wire   [7:0] tmp_28_fu_784_p5;
wire   [7:0] tmp_30_fu_803_p5;
wire   [7:0] tmp_31_fu_822_p5;
wire   [7:0] tmp_32_fu_877_p5;
wire   [7:0] tmp_33_fu_895_p5;
wire   [7:0] tmp_34_fu_913_p5;
wire   [18:0] p_shl1_fu_965_p3;
wire   [9:0] p_shl2_fu_977_p3;
wire   [19:0] p_shl1_cast_fu_973_p1;
wire   [19:0] p_shl2_cast_fu_985_p1;
wire   [19:0] r_V_52_0_1_fu_989_p2;
wire  signed [23:0] r_V_52_0_1_cast_fu_995_p1;
wire   [24:0] grp_fu_1286_p4;
wire   [18:0] p_shl3_fu_1009_p3;
wire   [9:0] p_shl4_fu_1021_p3;
wire   [19:0] p_shl3_cast_fu_1017_p1;
wire   [19:0] p_shl4_cast_fu_1029_p1;
wire   [19:0] r_V_52_1_fu_1033_p2;
wire  signed [23:0] r_V_52_1_cast_fu_1039_p1;
wire   [18:0] p_shl5_fu_1047_p3;
wire   [9:0] p_shl6_fu_1058_p3;
wire   [19:0] p_shl5_cast_fu_1054_p1;
wire   [19:0] p_shl6_cast_fu_1065_p1;
wire   [19:0] r_V_52_1_2_fu_1069_p2;
wire  signed [23:0] r_V_52_1_2_cast_fu_1075_p1;
wire   [25:0] tmp_510_1_cast_fu_1043_p1;
wire   [25:0] sum_V_0_2_cast_fu_1006_p1;
wire   [20:0] grp_fu_1297_p3;
wire   [24:0] tmp_510_1_2_cast_cas_fu_1079_p1;
wire   [24:0] tmp4_cast_fu_1093_p1;
wire   [24:0] tmp3_fu_1096_p2;
wire   [25:0] tmp2_fu_1087_p2;
wire   [25:0] tmp3_cast_fu_1102_p1;
wire   [18:0] p_shl_fu_1112_p3;
wire   [9:0] p_shl7_fu_1124_p3;
wire   [19:0] p_shl_cast_fu_1120_p1;
wire   [19:0] p_shl7_cast_fu_1132_p1;
wire   [19:0] r_V_52_2_1_fu_1136_p2;
wire  signed [23:0] r_V_52_2_1_cast_fu_1142_p1;
wire   [26:0] sum_V_2_cast_fu_1181_p1;
wire   [26:0] tmp5_cast_fu_1184_p1;
wire   [26:0] p_Val2_s_fu_1187_p2;
wire   [0:0] tmp_46_fu_1203_p3;
wire   [7:0] tmp_6_i_i_cast_fu_1211_p1;
wire   [7:0] p_Val2_1_fu_1193_p4;
wire   [4:0] tmp_35_fu_1221_p4;
wire   [0:0] tmp_47_fu_1237_p3;
wire   [7:0] p_Val2_2_fu_1215_p2;
wire   [0:0] tmp_48_fu_1251_p3;
wire   [0:0] rev2_fu_1245_p2;
wire   [0:0] Range1_all_zeros_fu_1231_p2;
wire   [0:0] not_carry_1_fu_1259_p2;
wire   [0:0] deleted_zeros_fu_1265_p2;
wire   [13:0] r_V_52_1_1_fu_1280_p0;
wire   [7:0] r_V_52_1_1_fu_1280_p1;
wire   [7:0] grp_fu_1286_p0;
wire   [7:0] grp_fu_1286_p1;
wire   [10:0] grp_fu_1286_p2;
wire   [23:0] grp_fu_1286_p3;
wire   [10:0] grp_fu_1297_p0;
wire   [7:0] grp_fu_1297_p1;
wire   [10:0] grp_fu_1305_p0;
wire   [7:0] grp_fu_1305_p1;
wire   [23:0] grp_fu_1305_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_111;
reg    ap_enable_state3_pp0_iter0_stage0;
reg    ap_enable_operation_137;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op152_store_state4;
reg    ap_enable_operation_152;
reg    ap_predicate_op159_store_state4;
reg    ap_enable_operation_159;
reg    ap_enable_operation_113;
reg    ap_enable_operation_141;
reg    ap_predicate_op150_store_state4;
reg    ap_enable_operation_150;
reg    ap_predicate_op157_store_state4;
reg    ap_enable_operation_157;
reg    ap_enable_operation_115;
reg    ap_enable_operation_144;
reg    ap_predicate_op148_store_state4;
reg    ap_enable_operation_148;
reg    ap_predicate_op156_store_state4;
reg    ap_enable_operation_156;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [8:0] grp_fu_1286_p00;
wire   [8:0] grp_fu_1286_p10;
wire   [24:0] grp_fu_1286_p30;
wire   [18:0] grp_fu_1297_p10;
wire   [18:0] grp_fu_1305_p10;
wire   [24:0] grp_fu_1305_p20;
wire   [20:0] r_V_52_1_1_fu_1280_p10;
reg    ap_condition_992;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 225 ),
    .AddressWidth( 8 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 225 ),
    .AddressWidth( 8 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 225 ),
    .AddressWidth( 8 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U31(
    .din0(right_border_buf_0_s_fu_172),
    .din1(right_border_buf_0_1_fu_176),
    .din2(8'd0),
    .din3(col_assign_6_t_fu_779_p2),
    .dout(tmp_28_fu_784_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U32(
    .din0(right_border_buf_0_3_fu_184),
    .din1(right_border_buf_0_4_fu_188),
    .din2(8'd0),
    .din3(col_assign_6_t_fu_779_p2),
    .dout(tmp_30_fu_803_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U33(
    .din0(right_border_buf_0_5_fu_192),
    .din1(right_border_buf_0_2_fu_180),
    .din2(8'd0),
    .din3(col_assign_6_t_fu_779_p2),
    .dout(tmp_31_fu_822_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U34(
    .din0(col_buf_0_val_0_0_fu_796_p3),
    .din1(col_buf_0_val_1_0_fu_815_p3),
    .din2(col_buf_0_val_2_0_fu_834_p3),
    .din3(row_assign_13_0_t_reg_1428),
    .dout(tmp_32_fu_877_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U35(
    .din0(col_buf_0_val_0_0_fu_796_p3),
    .din1(col_buf_0_val_1_0_fu_815_p3),
    .din2(col_buf_0_val_2_0_fu_834_p3),
    .din3(row_assign_13_1_t_reg_1433),
    .dout(tmp_33_fu_895_p5)
);

image_filter_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_hbi_U36(
    .din0(col_buf_0_val_0_0_fu_796_p3),
    .din1(col_buf_0_val_1_0_fu_815_p3),
    .din2(col_buf_0_val_2_0_fu_834_p3),
    .din3(row_assign_13_2_t_reg_1438),
    .dout(tmp_34_fu_913_p5)
);

image_filter_mul_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
image_filter_mul_ibs_U37(
    .din0(r_V_52_1_1_fu_1280_p0),
    .din1(r_V_52_1_1_fu_1280_p1),
    .dout(r_V_52_1_1_fu_1280_p2)
);

image_filter_ama_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
image_filter_ama_jbC_U38(
    .din0(grp_fu_1286_p0),
    .din1(grp_fu_1286_p1),
    .din2(grp_fu_1286_p2),
    .din3(grp_fu_1286_p3),
    .dout(grp_fu_1286_p4)
);

image_filter_mac_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
image_filter_mac_kbM_U39(
    .din0(grp_fu_1297_p0),
    .din1(grp_fu_1297_p1),
    .din2(r_V_52_1_1_reg_1508),
    .dout(grp_fu_1297_p3)
);

image_filter_mac_lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
image_filter_mac_lbW_U40(
    .din0(grp_fu_1305_p0),
    .din1(grp_fu_1305_p1),
    .din2(grp_fu_1305_p2),
    .dout(grp_fu_1305_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond460_i_fu_592_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond461_i_fu_300_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state4)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((exitcond461_i_fu_300_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_fu_592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_285 <= j_V_fu_598_p2;
    end else if (((exitcond461_i_fu_300_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_2_reg_285 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_274 <= i_V_reg_1394;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_274 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_fu_592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1461 <= brmerge_fu_744_p2;
        k_buf_0_val_3_addr_reg_1468 <= tmp_26_fu_749_p1;
        k_buf_0_val_4_addr_reg_1474 <= tmp_26_fu_749_p1;
        k_buf_0_val_5_addr_reg_1480 <= tmp_26_fu_749_p1;
        or_cond_i_i_reg_1452 <= or_cond_i_i_fu_650_p2;
        or_cond_i_reg_1486 <= or_cond_i_fu_756_p2;
        tmp_43_reg_1456 <= tmp_43_fu_740_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond460_i_reg_1443 <= exitcond460_i_fu_592_p2;
        exitcond460_i_reg_1443_pp0_iter1_reg <= exitcond460_i_reg_1443;
        or_cond_i_reg_1486_pp0_iter1_reg <= or_cond_i_reg_1486;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1394 <= i_V_fu_306_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_300_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1408 <= icmp_fu_334_p2;
        row_assign_13_0_t_reg_1428 <= row_assign_13_0_t_fu_506_p2;
        row_assign_13_1_t_reg_1433 <= row_assign_13_1_t_fu_544_p2;
        row_assign_13_2_t_reg_1438 <= row_assign_13_2_t_fu_582_p2;
        tmp_2_reg_1413 <= tmp_2_fu_340_p2;
        tmp_3_reg_1421 <= tmp_3_fu_352_p2;
        tmp_424_0_not_reg_1403 <= tmp_424_0_not_fu_318_p2;
        tmp_468_1_reg_1417 <= tmp_468_1_fu_346_p2;
        tmp_s_reg_1399 <= tmp_s_fu_312_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_reg_1486_pp0_iter2_reg <= or_cond_i_reg_1486_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1486 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_52_1_1_reg_1508 <= r_V_52_1_1_fu_1280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_1_fu_176 <= right_border_buf_0_s_fu_172;
        right_border_buf_0_2_fu_180 <= right_border_buf_0_5_fu_192;
        right_border_buf_0_3_fu_184 <= col_buf_0_val_1_0_fu_815_p3;
        right_border_buf_0_4_fu_188 <= right_border_buf_0_3_fu_184;
        right_border_buf_0_5_fu_192 <= col_buf_0_val_2_0_fu_834_p3;
        right_border_buf_0_s_fu_172 <= col_buf_0_val_0_0_fu_796_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1443 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_16_reg_1513 <= src_kernel_win_0_va_2_fu_156;
        src_kernel_win_0_va_6_reg_1490 <= src_kernel_win_0_va_6_fu_888_p3;
        src_kernel_win_0_va_7_reg_1496 <= src_kernel_win_0_va_7_fu_906_p3;
        src_kernel_win_0_va_8_reg_1502 <= src_kernel_win_0_va_8_fu_924_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1443_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_152 <= src_kernel_win_0_va_fu_148;
        src_kernel_win_0_va_3_fu_160 <= src_kernel_win_0_va_16_reg_1513;
        src_kernel_win_0_va_4_fu_164 <= src_kernel_win_0_va_8_reg_1502;
        src_kernel_win_0_va_5_fu_168 <= src_kernel_win_0_va_4_fu_164;
        src_kernel_win_0_va_fu_148 <= src_kernel_win_0_va_6_reg_1490;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_2_fu_156 <= src_kernel_win_0_va_7_fu_906_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1486_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_2_reg_1518 <= sum_V_2_fu_1106_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1486_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp5_reg_1523 <= grp_fu_1305_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond461_i_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond461_i_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1413 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1413 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_468_1_reg_1417 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_992)) begin
        if (((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_468_1_reg_1417 == 1'd1) & (icmp_reg_1408 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_468_1_reg_1417 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1413 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_992)) begin
        if (((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_2_reg_1413 == 1'd1) & (icmp_reg_1408 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1413 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1486_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1486_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op158_read_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op147_read_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond461_i_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_626_p1 = ImagLoc_x_fu_620_p2;

assign ImagLoc_x_fu_620_p2 = ($signed(9'd511) + $signed(t_V_3_cast_fu_588_p1));

assign Range1_all_zeros_fu_1231_p2 = ((tmp_35_fu_1221_p4 == 5'd0) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((or_cond_i_reg_1486_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op158_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op147_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((or_cond_i_reg_1486_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op158_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op147_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((or_cond_i_reg_1486_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op158_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op147_read_state4 == 1'b1)))));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op158_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op147_read_state4 == 1'b1)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter3 = ((or_cond_i_reg_1486_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_992 = ((or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_111 = (exitcond460_i_fu_592_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_113 = (exitcond460_i_fu_592_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_115 = (exitcond460_i_fu_592_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_137 = (exitcond460_i_reg_1443 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_141 = (exitcond460_i_reg_1443 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_144 = (exitcond460_i_reg_1443 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_148 = (ap_predicate_op148_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_150 = (ap_predicate_op150_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_152 = (ap_predicate_op152_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_156 = (ap_predicate_op156_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_157 = (ap_predicate_op157_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_159 = (ap_predicate_op159_store_state4 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state3_pp0_iter0_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op147_read_state4 = ((or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0));
end

always @ (*) begin
    ap_predicate_op148_store_state4 = ((tmp_2_reg_1413 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0));
end

always @ (*) begin
    ap_predicate_op150_store_state4 = ((tmp_468_1_reg_1417 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0));
end

always @ (*) begin
    ap_predicate_op152_store_state4 = ((tmp_2_reg_1413 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (icmp_reg_1408 == 1'd0) & (exitcond460_i_reg_1443 == 1'd0));
end

always @ (*) begin
    ap_predicate_op156_store_state4 = ((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0));
end

always @ (*) begin
    ap_predicate_op157_store_state4 = ((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0));
end

always @ (*) begin
    ap_predicate_op158_read_state4 = ((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0));
end

always @ (*) begin
    ap_predicate_op159_store_state4 = ((tmp_s_reg_1399 == 1'd1) & (icmp_reg_1408 == 1'd1) & (or_cond_i_i_reg_1452 == 1'd1) & (exitcond460_i_reg_1443 == 1'd0));
end

assign brmerge_fu_744_p2 = (tmp_424_0_not_reg_1403 | tmp_22_fu_644_p2);

assign col_assign_6_t_fu_779_p2 = (2'd0 - tmp_43_reg_1456);

assign col_assign_cast_fu_736_p1 = x_fu_728_p3;

assign col_buf_0_val_0_0_fu_796_p3 = ((brmerge_reg_1461[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_28_fu_784_p5);

assign col_buf_0_val_1_0_fu_815_p3 = ((brmerge_reg_1461[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_30_fu_803_p5);

assign col_buf_0_val_2_0_fu_834_p3 = ((brmerge_reg_1461[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_31_fu_822_p5);

assign deleted_zeros_fu_1265_p2 = (not_carry_1_fu_1259_p2 & Range1_all_zeros_fu_1231_p2);

assign exitcond460_i_fu_592_p2 = ((t_V_2_reg_285 == 8'd227) ? 1'b1 : 1'b0);

assign exitcond461_i_fu_300_p2 = ((t_V_reg_274 == 8'd227) ? 1'b1 : 1'b0);

assign grp_fu_1286_p0 = grp_fu_1286_p00;

assign grp_fu_1286_p00 = src_kernel_win_0_va_8_reg_1502;

assign grp_fu_1286_p1 = grp_fu_1286_p10;

assign grp_fu_1286_p10 = src_kernel_win_0_va_5_fu_168;

assign grp_fu_1286_p2 = 19'd936;

assign grp_fu_1286_p3 = grp_fu_1286_p30;

assign grp_fu_1286_p30 = $unsigned(r_V_52_0_1_cast_fu_995_p1);

assign grp_fu_1297_p0 = 19'd936;

assign grp_fu_1297_p1 = grp_fu_1297_p10;

assign grp_fu_1297_p10 = src_kernel_win_0_va_1_fu_152;

assign grp_fu_1305_p0 = 19'd936;

assign grp_fu_1305_p1 = grp_fu_1305_p10;

assign grp_fu_1305_p10 = src_kernel_win_0_va_6_reg_1490;

assign grp_fu_1305_p2 = grp_fu_1305_p20;

assign grp_fu_1305_p20 = $unsigned(r_V_52_2_1_cast_fu_1142_p1);

assign i_V_fu_306_p2 = (t_V_reg_274 + 8'd1);

assign icmp1_fu_614_p2 = ((tmp_40_fu_604_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_fu_334_p2 = ((tmp_6_fu_324_p4 != 7'd0) ? 1'b1 : 1'b0);

assign j_V_fu_598_p2 = (t_V_2_reg_285 + 8'd1);

assign k_buf_0_val_3_address0 = tmp_26_fu_749_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1468;

assign k_buf_0_val_4_address0 = tmp_26_fu_749_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_1474;

assign k_buf_0_val_5_address0 = tmp_26_fu_749_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_1480;

assign not_carry_1_fu_1259_p2 = (tmp_48_fu_1251_p3 | rev2_fu_1245_p2);

assign or_cond_i496_i_fu_394_p2 = (tmp_7_fu_388_p2 & rev_fu_382_p2);

assign or_cond_i_fu_756_p2 = (icmp_reg_1408 & icmp1_fu_614_p2);

assign or_cond_i_i_fu_650_p2 = (tmp_22_fu_644_p2 & rev1_fu_638_p2);

assign p_Val2_1_fu_1193_p4 = {{p_Val2_s_fu_1187_p2[21:14]}};

assign p_Val2_2_fu_1215_p2 = (tmp_6_i_i_cast_fu_1211_p1 + p_Val2_1_fu_1193_p4);

assign p_Val2_s_fu_1187_p2 = (sum_V_2_cast_fu_1181_p1 + tmp5_cast_fu_1184_p1);

assign p_assign_14_1_fu_438_p2 = ($signed(9'd510) + $signed(t_V_cast_fu_296_p1));

assign p_assign_14_2_fu_464_p2 = ($signed(9'd509) + $signed(t_V_cast_fu_296_p1));

assign p_assign_1_fu_432_p2 = (2'd0 - tmp_12_fu_422_p1);

assign p_assign_3_fu_664_p2 = (9'd1 - t_V_3_cast_fu_588_p1);

assign p_assign_4_fu_692_p2 = ($signed(10'd448) - $signed(p_p2_i_i_cast_fu_682_p1));

assign p_assign_5_fu_698_p3 = ((or_cond_i_i_fu_650_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_626_p1 : p_assign_4_fu_692_p2);

assign p_assign_s_fu_408_p2 = (9'd1 - t_V_cast_fu_296_p1);

assign p_dst_data_stream_V_din = ((deleted_zeros_fu_1265_p2[0:0] === 1'b1) ? p_Val2_2_fu_1215_p2 : 8'd255);

assign p_p2_i497_i_fu_414_p3 = ((tmp_11_fu_400_p3[0:0] === 1'b1) ? p_assign_s_fu_408_p2 : tmp_5_fu_362_p2);

assign p_p2_i497_i_p_assign_s_fu_490_p3 = ((tmp_9_fu_426_p2[0:0] === 1'b1) ? tmp_12_fu_422_p1 : p_assign_1_fu_432_p2);

assign p_p2_i_i_cast6_fu_678_p1 = p_p2_i_i_fu_670_p3;

assign p_p2_i_i_cast_fu_682_p1 = p_p2_i_i_fu_670_p3;

assign p_p2_i_i_fu_670_p3 = ((tmp_42_fu_656_p3[0:0] === 1'b1) ? p_assign_3_fu_664_p2 : ImagLoc_x_fu_620_p2);

assign p_shl1_cast_fu_973_p1 = p_shl1_fu_965_p3;

assign p_shl1_fu_965_p3 = {{src_kernel_win_0_va_4_fu_164}, {11'd0}};

assign p_shl2_cast_fu_985_p1 = p_shl2_fu_977_p3;

assign p_shl2_fu_977_p3 = {{src_kernel_win_0_va_4_fu_164}, {2'd0}};

assign p_shl3_cast_fu_1017_p1 = p_shl3_fu_1009_p3;

assign p_shl3_fu_1009_p3 = {{src_kernel_win_0_va_3_fu_160}, {11'd0}};

assign p_shl4_cast_fu_1029_p1 = p_shl4_fu_1021_p3;

assign p_shl4_fu_1021_p3 = {{src_kernel_win_0_va_3_fu_160}, {2'd0}};

assign p_shl5_cast_fu_1054_p1 = p_shl5_fu_1047_p3;

assign p_shl5_fu_1047_p3 = {{src_kernel_win_0_va_7_reg_1496}, {11'd0}};

assign p_shl6_cast_fu_1065_p1 = p_shl6_fu_1058_p3;

assign p_shl6_fu_1058_p3 = {{src_kernel_win_0_va_7_reg_1496}, {2'd0}};

assign p_shl7_cast_fu_1132_p1 = p_shl7_fu_1124_p3;

assign p_shl7_fu_1124_p3 = {{src_kernel_win_0_va_fu_148}, {2'd0}};

assign p_shl_cast_fu_1120_p1 = p_shl_fu_1112_p3;

assign p_shl_fu_1112_p3 = {{src_kernel_win_0_va_fu_148}, {11'd0}};

assign r_V_52_0_1_cast_fu_995_p1 = $signed(r_V_52_0_1_fu_989_p2);

assign r_V_52_0_1_fu_989_p2 = (p_shl1_cast_fu_973_p1 - p_shl2_cast_fu_985_p1);

assign r_V_52_1_1_fu_1280_p0 = 21'd4465;

assign r_V_52_1_1_fu_1280_p1 = r_V_52_1_1_fu_1280_p10;

assign r_V_52_1_1_fu_1280_p10 = src_kernel_win_0_va_2_fu_156;

assign r_V_52_1_2_cast_fu_1075_p1 = $signed(r_V_52_1_2_fu_1069_p2);

assign r_V_52_1_2_fu_1069_p2 = (p_shl5_cast_fu_1054_p1 - p_shl6_cast_fu_1065_p1);

assign r_V_52_1_cast_fu_1039_p1 = $signed(r_V_52_1_fu_1033_p2);

assign r_V_52_1_fu_1033_p2 = (p_shl3_cast_fu_1017_p1 - p_shl4_cast_fu_1029_p1);

assign r_V_52_2_1_cast_fu_1142_p1 = $signed(r_V_52_2_1_fu_1136_p2);

assign r_V_52_2_1_fu_1136_p2 = (p_shl_cast_fu_1120_p1 - p_shl7_cast_fu_1132_p1);

assign rev1_fu_638_p2 = (tmp_41_fu_630_p3 ^ 1'd1);

assign rev2_fu_1245_p2 = (tmp_47_fu_1237_p3 ^ 1'd1);

assign rev_fu_382_p2 = (tmp_10_fu_374_p3 ^ 1'd1);

assign row_assign_13_0_t_fu_506_p2 = (2'd0 - y_fu_498_p3);

assign row_assign_13_1_t_fu_544_p2 = (2'd0 - tmp_13_fu_536_p3);

assign row_assign_13_2_t_fu_582_p2 = (2'd0 - tmp_18_fu_574_p3);

assign sel_tmp7_fu_716_p2 = (tmp_41_fu_630_p3 | tmp_26_not_fu_710_p2);

assign sel_tmp8_fu_722_p2 = (tmp_23_fu_686_p2 & sel_tmp7_fu_716_p2);

assign sel_tmp_cast_fu_706_p1 = p_assign_5_fu_698_p3;

assign src_kernel_win_0_va_6_fu_888_p3 = ((tmp_3_reg_1421[0:0] === 1'b1) ? tmp_32_fu_877_p5 : col_buf_0_val_0_0_fu_796_p3);

assign src_kernel_win_0_va_7_fu_906_p3 = ((tmp_3_reg_1421[0:0] === 1'b1) ? tmp_33_fu_895_p5 : col_buf_0_val_1_0_fu_815_p3);

assign src_kernel_win_0_va_8_fu_924_p3 = ((tmp_3_reg_1421[0:0] === 1'b1) ? tmp_34_fu_913_p5 : col_buf_0_val_2_0_fu_834_p3);

assign sum_V_0_2_cast_fu_1006_p1 = grp_fu_1286_p4;

assign sum_V_2_cast_fu_1181_p1 = sum_V_2_reg_1518;

assign sum_V_2_fu_1106_p2 = (tmp2_fu_1087_p2 + tmp3_cast_fu_1102_p1);

assign t_V_3_cast_fu_588_p1 = t_V_2_reg_285;

assign t_V_cast_fu_296_p1 = t_V_reg_274;

assign tmp2_fu_1087_p2 = (tmp_510_1_cast_fu_1043_p1 + sum_V_0_2_cast_fu_1006_p1);

assign tmp3_cast_fu_1102_p1 = tmp3_fu_1096_p2;

assign tmp3_fu_1096_p2 = (tmp_510_1_2_cast_cas_fu_1079_p1 + tmp4_cast_fu_1093_p1);

assign tmp4_cast_fu_1093_p1 = grp_fu_1297_p3;

assign tmp5_cast_fu_1184_p1 = tmp5_reg_1523;

assign tmp_10_fu_374_p3 = tmp_5_fu_362_p2[32'd8];

assign tmp_11_fu_400_p3 = tmp_5_fu_362_p2[32'd8];

assign tmp_12_fu_422_p1 = p_p2_i497_i_fu_414_p3[1:0];

assign tmp_13_fu_536_p3 = ((tmp_14_fu_444_p3[0:0] === 1'b1) ? tmp_4_fu_528_p3 : tmp_1_fu_512_p2);

assign tmp_14_fu_444_p3 = p_assign_14_1_fu_438_p2[32'd8];

assign tmp_15_fu_452_p3 = p_assign_14_1_fu_438_p2[32'd8];

assign tmp_16_fu_550_p2 = (2'd1 + tmp_8_fu_358_p1);

assign tmp_17_fu_566_p3 = ((tmp_24_fu_478_p3[0:0] === 1'b1) ? tmp_38_fu_556_p2 : tmp_39_fu_562_p1);

assign tmp_18_fu_574_p3 = ((tmp_21_fu_470_p3[0:0] === 1'b1) ? tmp_17_fu_566_p3 : tmp_16_fu_550_p2);

assign tmp_1_fu_512_p2 = (tmp_8_fu_358_p1 ^ 2'd2);

assign tmp_20_fu_460_p1 = t_V_reg_274[1:0];

assign tmp_21_fu_470_p3 = p_assign_14_2_fu_464_p2[32'd8];

assign tmp_22_fu_644_p2 = (($signed(ImagLoc_x_fu_620_p2) < $signed(9'd225)) ? 1'b1 : 1'b0);

assign tmp_23_fu_686_p2 = (($signed(p_p2_i_i_fu_670_p3) < $signed(9'd225)) ? 1'b1 : 1'b0);

assign tmp_24_fu_478_p3 = p_assign_14_2_fu_464_p2[32'd8];

assign tmp_25_fu_486_p1 = t_V_reg_274[1:0];

assign tmp_26_fu_749_p1 = $unsigned(col_assign_cast_fu_736_p1);

assign tmp_26_not_fu_710_p2 = (tmp_22_fu_644_p2 ^ 1'd1);

assign tmp_27_fu_518_p2 = ($signed(2'd2) - $signed(tmp_20_fu_460_p1));

assign tmp_29_fu_524_p1 = p_assign_14_1_fu_438_p2[1:0];

assign tmp_2_fu_340_p2 = ((t_V_reg_274 == 8'd1) ? 1'b1 : 1'b0);

assign tmp_35_fu_1221_p4 = {{p_Val2_s_fu_1187_p2[26:22]}};

assign tmp_38_fu_556_p2 = (tmp_25_fu_486_p1 ^ 2'd3);

assign tmp_39_fu_562_p1 = p_assign_14_2_fu_464_p2[1:0];

assign tmp_3_fu_352_p2 = ((t_V_reg_274 > 8'd225) ? 1'b1 : 1'b0);

assign tmp_40_fu_604_p4 = {{t_V_2_reg_285[7:1]}};

assign tmp_41_fu_630_p3 = ImagLoc_x_fu_620_p2[32'd8];

assign tmp_424_0_not_fu_318_p2 = (tmp_s_fu_312_p2 ^ 1'd1);

assign tmp_42_fu_656_p3 = ImagLoc_x_fu_620_p2[32'd8];

assign tmp_43_fu_740_p1 = x_fu_728_p3[1:0];

assign tmp_468_1_fu_346_p2 = ((t_V_reg_274 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_46_fu_1203_p3 = p_Val2_s_fu_1187_p2[32'd13];

assign tmp_47_fu_1237_p3 = p_Val2_s_fu_1187_p2[32'd21];

assign tmp_48_fu_1251_p3 = p_Val2_2_fu_1215_p2[32'd7];

assign tmp_4_fu_528_p3 = ((tmp_15_fu_452_p3[0:0] === 1'b1) ? tmp_27_fu_518_p2 : tmp_29_fu_524_p1);

assign tmp_510_1_2_cast_cas_fu_1079_p1 = $unsigned(r_V_52_1_2_cast_fu_1075_p1);

assign tmp_510_1_cast_fu_1043_p1 = $unsigned(r_V_52_1_cast_fu_1039_p1);

assign tmp_5_fu_362_p2 = ($signed(9'd511) + $signed(t_V_cast_fu_296_p1));

assign tmp_6_fu_324_p4 = {{t_V_reg_274[7:1]}};

assign tmp_6_i_i_cast_fu_1211_p1 = tmp_46_fu_1203_p3;

assign tmp_72_cast_fu_368_p2 = ($signed(2'd3) + $signed(tmp_8_fu_358_p1));

assign tmp_7_fu_388_p2 = (($signed(tmp_5_fu_362_p2) < $signed(9'd225)) ? 1'b1 : 1'b0);

assign tmp_8_fu_358_p1 = t_V_reg_274[1:0];

assign tmp_9_fu_426_p2 = (($signed(p_p2_i497_i_fu_414_p3) < $signed(9'd225)) ? 1'b1 : 1'b0);

assign tmp_s_fu_312_p2 = ((t_V_reg_274 < 8'd225) ? 1'b1 : 1'b0);

assign x_fu_728_p3 = ((sel_tmp8_fu_722_p2[0:0] === 1'b1) ? p_p2_i_i_cast6_fu_678_p1 : sel_tmp_cast_fu_706_p1);

assign y_fu_498_p3 = ((or_cond_i496_i_fu_394_p2[0:0] === 1'b1) ? tmp_72_cast_fu_368_p2 : p_p2_i497_i_p_assign_s_fu_490_p3);

endmodule //Filter2D_1
